// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  home_title: defineAsyncComponent(() => import("./HomeTitle/index.vue")),
  project: defineAsyncComponent(() => import("./Project/index.vue")),
});
