// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticlesDocumentDataSlicesSlice = ArticleSlice;

/**
 * Content for Articles documents
 */
interface ArticlesDocumentData {
  /**
   * Slice Zone field in *Articles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticlesDocumentDataSlicesSlice> /**
   * Meta Title field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: articles.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: articles.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Articles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Articles document from Prismic
 *
 * - **API ID**: `articles`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticlesDocumentData>,
    "articles",
    Lang
  >;

type HomeDocumentDataSlicesSlice = HomeSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Titolo Introduttivo field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Es. Joshua Rte.
   * - **API ID Path**: home.intro_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro_title: prismic.KeyTextField;

  /**
   * Testo Introduttivo field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrizione breve
   * - **API ID Path**: home.intro_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro_text: prismic.RichTextField;

  /**
   * Pulsante Introduttivo field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link al pulsante
   * - **API ID Path**: home.intro_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  intro_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ProjectsDocumentDataSlicesSlice = ProjectSlice;

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Slice Zone field in *Projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice> /**
   * Meta Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Content for Work List documents
 */
interface WorkListDocumentData {
  /**
   * Work Company field in *Work List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_list.work_company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_company: prismic.KeyTextField;

  /**
   * Work Company URL field in *Work List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: work_list.work_company_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  work_company_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Work Role field in *Work List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_list.work_role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  work_role: prismic.RichTextField;

  /**
   * Work Description field in *Work List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_list.work_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  work_description: prismic.RichTextField;
}

/**
 * Work List document from Prismic
 *
 * - **API ID**: `work_list`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WorkListDocumentData>,
    "work_list",
    Lang
  >;

export type AllDocumentTypes =
  | ArticlesDocument
  | HomeDocument
  | ProjectsDocument
  | WorkListDocument;

/**
 * Primary content in *Article → Default → Primary*
 */
export interface ArticleSliceDefaultPrimary {
  /**
   * Article Title field in *Article → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.default.primary.article
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  article: prismic.KeyTextField;
}

/**
 * Default variation for Article Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Article*
 */
type ArticleSliceVariation = ArticleSliceDefault;

/**
 * Article Shared Slice
 *
 * - **API ID**: `article`
 * - **Description**: Article
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSlice = prismic.SharedSlice<
  "article",
  ArticleSliceVariation
>;

/**
 * Primary content in *Home → Default → Primary*
 */
export interface HomeSliceDefaultPrimary {
  /**
   * Hero Image field in *Home → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Intro Text field in *Home → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro_text: prismic.KeyTextField;

  /**
   * Intro Description field in *Home → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.intro_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro_description: prismic.RichTextField;

  /**
   * Intro Button field in *Home → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.intro_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  intro_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Bio Heading field in *Home → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.bio_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bio_heading: prismic.KeyTextField;

  /**
   * Bio Content field in *Home → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.bio_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio_content: prismic.RichTextField;

  /**
   * Projects Heading field in *Home → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: I miei progetti
   * - **API ID Path**: home.default.primary.projects_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  projects_heading: prismic.KeyTextField;

  /**
   * Projects List field in *Home → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.projects_list
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projects_list: prismic.ContentRelationshipField<"projects">;
}

/**
 * Default variation for Home Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Home*
 */
type HomeSliceVariation = HomeSliceDefault;

/**
 * Home Shared Slice
 *
 * - **API ID**: `home`
 * - **Description**: Home
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSlice = prismic.SharedSlice<"home", HomeSliceVariation>;

/**
 * Primary content in *PersonalProjects → Default → Primary*
 */
export interface PersonalProjectsSliceDefaultPrimary {
  /**
   * Projects Heading field in *PersonalProjects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: <personal_projects/>
   * - **API ID Path**: personal_projects.default.primary.projects_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  projects_heading: prismic.KeyTextField;
}

/**
 * Primary content in *PersonalProjects → Items*
 */
export interface PersonalProjectsSliceDefaultItem {
  /**
   * Project Name field in *PersonalProjects → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome del progetto
   * - **API ID Path**: personal_projects.items[].project_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_name: prismic.KeyTextField;

  /**
   * Project URL field in *PersonalProjects → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL del progetto
   * - **API ID Path**: personal_projects.items[].project_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Role field in *PersonalProjects → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ruolo nel progetto
   * - **API ID Path**: personal_projects.items[].project_role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_role: prismic.KeyTextField;

  /**
   * Period field in *PersonalProjects → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Periodo del progetto
   * - **API ID Path**: personal_projects.items[].project_period
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_period: prismic.KeyTextField;

  /**
   * Description field in *PersonalProjects → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrizione del progetto
   * - **API ID Path**: personal_projects.items[].project_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_description: prismic.RichTextField;
}

/**
 * Default variation for PersonalProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PersonalProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PersonalProjectsSliceDefaultPrimary>,
  Simplify<PersonalProjectsSliceDefaultItem>
>;

/**
 * Slice variation for *PersonalProjects*
 */
type PersonalProjectsSliceVariation = PersonalProjectsSliceDefault;

/**
 * PersonalProjects Shared Slice
 *
 * - **API ID**: `personal_projects`
 * - **Description**: Personal Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PersonalProjectsSlice = prismic.SharedSlice<
  "personal_projects",
  PersonalProjectsSliceVariation
>;

/**
 * Primary content in *Project → Default → Primary*
 */
export interface ProjectSliceDefaultPrimary {
  /**
   * ImageUrl field in *Project → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.imageurl
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageurl: prismic.ImageField<never>;

  /**
   * Name field in *Project → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * JobDescription field in *Project → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.jobdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  jobdescription: prismic.RichTextField;

  /**
   * URL field in *Project → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Project*
 */
type ProjectSliceVariation = ProjectSliceDefault;

/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: Project
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSlice = prismic.SharedSlice<
  "project",
  ProjectSliceVariation
>;

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * Skills Heading field in *Skills → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: <skills/>
   * - **API ID Path**: skills.default.primary.skills_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skills_heading: prismic.KeyTextField;
}

/**
 * Primary content in *Skills → Items*
 */
export interface SkillsSliceDefaultItem {
  /**
   * Skill Title field in *Skills → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome della competenza
   * - **API ID Path**: skills.items[].skill_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skill_title: prismic.KeyTextField;

  /**
   * Technologies field in *Skills → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tecnologie utilizzate
   * - **API ID Path**: skills.items[].skill_technologies
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skill_technologies: prismic.KeyTextField;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  Simplify<SkillsSliceDefaultItem>
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

/**
 * Primary content in *WorkExperience → Default → Primary*
 */
export interface WorkExperienceSliceDefaultPrimary {
  /**
   * Work Heading field in *WorkExperience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: <work/>
   * - **API ID Path**: work_experience.default.primary.work_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_heading: prismic.KeyTextField;
}

/**
 * Primary content in *WorkExperience → Items*
 */
export interface WorkExperienceSliceDefaultItem {
  /**
   * Company Name field in *WorkExperience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome dell'azienda
   * - **API ID Path**: work_experience.items[].company_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Company URL field in *WorkExperience → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL dell'azienda
   * - **API ID Path**: work_experience.items[].company_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Position field in *WorkExperience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Posizione ricoperta
   * - **API ID Path**: work_experience.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Period field in *WorkExperience → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Periodo di lavoro
   * - **API ID Path**: work_experience.items[].period
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  period: prismic.KeyTextField;

  /**
   * Description field in *WorkExperience → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrizione del ruolo
   * - **API ID Path**: work_experience.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for WorkExperience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkExperienceSliceDefaultPrimary>,
  Simplify<WorkExperienceSliceDefaultItem>
>;

/**
 * Slice variation for *WorkExperience*
 */
type WorkExperienceSliceVariation = WorkExperienceSliceDefault;

/**
 * WorkExperience Shared Slice
 *
 * - **API ID**: `work_experience`
 * - **Description**: Work Experience
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkExperienceSlice = prismic.SharedSlice<
  "work_experience",
  WorkExperienceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticlesDocument,
      ArticlesDocumentData,
      ArticlesDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataSlicesSlice,
      WorkListDocument,
      WorkListDocumentData,
      AllDocumentTypes,
      ArticleSlice,
      ArticleSliceDefaultPrimary,
      ArticleSliceVariation,
      ArticleSliceDefault,
      HomeSlice,
      HomeSliceDefaultPrimary,
      HomeSliceVariation,
      HomeSliceDefault,
      PersonalProjectsSlice,
      PersonalProjectsSliceDefaultPrimary,
      PersonalProjectsSliceDefaultItem,
      PersonalProjectsSliceVariation,
      PersonalProjectsSliceDefault,
      ProjectSlice,
      ProjectSliceDefaultPrimary,
      ProjectSliceVariation,
      ProjectSliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimary,
      SkillsSliceDefaultItem,
      SkillsSliceVariation,
      SkillsSliceDefault,
      WorkExperienceSlice,
      WorkExperienceSliceDefaultPrimary,
      WorkExperienceSliceDefaultItem,
      WorkExperienceSliceVariation,
      WorkExperienceSliceDefault,
    };
  }
}
